apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: dp-kafka-rest
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{ image }}
  port: 8082
  prometheus:
    enabled: false
  liveness:
    path: /brokers
  readiness:
    path: /brokers
  startup:
    path: /brokers
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  kafka:
    pool: {{ kafka.pool }}
